"""
AURA Conversation & Reasoning Engine (Milestone 6)
Coordinates the Context Manager, Knowledge Retriever, and Intent Classifier
to generate natural language responses grounded in real-time visual perception.
"""

import os
import time
import logging
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any

from knowledge.retriever import KnowledgeRetriever
from knowledge.sources import KnowledgeItem
from .context import ContextManager, ObjectEntity, SceneContext
from .intent import IntentClassifier, IntentType, ParsedQuery

logger = logging.getLogger(__name__)


@dataclass
class ConversationResponse:
    """
    Structured natural-language response generated by AURA.
    """
    query: str
    intent: IntentType
    response_text: str
    target_entity: Optional[ObjectEntity] = None
    knowledge_item: Optional[KnowledgeItem] = None
    sources: List[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query,
            "intent": self.intent.value,
            "response_text": self.response_text,
            "target_entity": self.target_entity.to_dict() if self.target_entity else None,
            "knowledge_item": self.knowledge_item.to_dict() if self.knowledge_item else None,
            "sources": self.sources,
            "timestamp": round(self.timestamp, 2),
        }


class ConversationEngine:
    """
    Core reasoning and conversational intelligence engine for AURA.
    Provides 100% offline grounded reasoning with optional pluggable LLM support.
    """

    def __init__(
        self,
        context_manager: Optional[ContextManager] = None,
        knowledge_retriever: Optional[KnowledgeRetriever] = None,
        intent_classifier: Optional[IntentClassifier] = None,
    ):
        self.context_manager = context_manager or ContextManager()
        self.knowledge_retriever = knowledge_retriever or KnowledgeRetriever()
        self.intent_classifier = intent_classifier or IntentClassifier()

    def respond(self, query: str) -> ConversationResponse:
        """
        Processes a user question, parses intent, consults context & knowledge,
        and returns a grounded natural language response.
        """
        if not query or not query.strip():
            return ConversationResponse(
                query="",
                intent=IntentType.GENERAL_QA,
                response_text="I am listening. How can I assist you with what I see?",
            )

        # 1. Parse intent
        parsed = self.intent_classifier.classify(query)
        logger.info(f"Parsed intent '{parsed.intent.value}' for query: '{query}'")

        # 2. Record user query in conversation memory
        self.context_manager.add_conversation_turn("user", query)

        # 3. Route to specialized intent handlers
        if parsed.intent == IntentType.SCENE_SUMMARY:
            resp = self._handle_scene_summary(parsed)
        elif parsed.intent == IntentType.OBJECT_INFO:
            resp = self._handle_object_info(parsed)
        elif parsed.intent == IntentType.OBJECT_LOCATION:
            resp = self._handle_object_location(parsed)
        elif parsed.intent == IntentType.OBJECT_COUNT:
            resp = self._handle_object_count(parsed)
        elif parsed.intent == IntentType.OCR_READ:
            resp = self._handle_ocr_read(parsed)
        elif parsed.intent == IntentType.RELIABILITY_CHECK:
            resp = self._handle_reliability_check(parsed)
        elif parsed.intent == IntentType.VOICE_CONTROL:
            resp = self._handle_voice_control(parsed)
        else:
            resp = self._handle_general_qa(parsed)

        # 4. Record assistant response in conversation memory
        self.context_manager.add_conversation_turn("assistant", resp.response_text)

        return resp

    def _handle_scene_summary(self, parsed: ParsedQuery) -> ConversationResponse:
        scene = self.context_manager.latest_scene
        if not scene:
            text = "No visual scene has been observed yet."
        else:
            text = scene.summary()

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            sources=["vision_engine", "tracker", "ocr"],
        )

    def _handle_object_info(self, parsed: ParsedQuery) -> ConversationResponse:
        # Resolve target object
        target_entity = self.context_manager.resolve_reference(parsed.raw_query)
        entity_name = target_entity.class_name if target_entity else (parsed.target_object or "object")

        # Retrieve knowledge
        knowledge = self.knowledge_retriever.retrieve(entity_name)

        if target_entity and knowledge:
            text = (
                f"I see a {target_entity.describe()}. "
                f"{knowledge.summary} (Category: {knowledge.category})."
            )
            sources = ["context_manager", knowledge.source]
        elif target_entity:
            text = f"I see a {target_entity.describe()} with {int(target_entity.confidence * 100)}% detection confidence."
            sources = ["context_manager"]
        elif knowledge:
            text = f"{knowledge.title}: {knowledge.summary}"
            sources = [knowledge.source]
        else:
            text = f"I cannot currently see or find information about '{parsed.raw_query}' in the current view."
            sources = []

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            target_entity=target_entity,
            knowledge_item=knowledge,
            sources=sources,
        )

    def _handle_object_location(self, parsed: ParsedQuery) -> ConversationResponse:
        target_entity = self.context_manager.resolve_reference(parsed.raw_query)

        if target_entity:
            track_str = f" (Track #{target_entity.track_id})" if target_entity.track_id is not None else ""
            text = f"The {target_entity.class_name}{track_str} is located in the {target_entity.spatial_pos} region of your view."
        else:
            scene = self.context_manager.latest_scene
            visible_names = [e.class_name for e in scene.entities] if scene else []
            if visible_names:
                text = f"I cannot find that specific object. Currently visible objects are: {', '.join(set(visible_names))}."
            else:
                text = "There are no objects currently detected in the scene."

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            target_entity=target_entity,
            sources=["context_manager", "spatial_reasoner"],
        )

    def _handle_object_count(self, parsed: ParsedQuery) -> ConversationResponse:
        scene = self.context_manager.latest_scene
        if not scene or not scene.entities:
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text="There are 0 objects detected in the current view.",
                sources=["context_manager"],
            )

        if parsed.target_object:
            matching = [e for e in scene.entities if parsed.target_object.lower() in e.class_name.lower()]
            count = len(matching)
            plural = "s" if count != 1 and not parsed.target_object.endswith("s") else ""
            text = f"I count {count} {parsed.target_object}{plural} in the current view."
        else:
            total = len(scene.entities)
            counts_str = ", ".join(f"{c} {n}" for n, c in scene.object_counts.items())
            text = f"I count {total} total objects in view ({counts_str})."

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            sources=["context_manager"],
        )

    def _handle_ocr_read(self, parsed: ParsedQuery) -> ConversationResponse:
        scene = self.context_manager.latest_scene
        target_entity = self.context_manager.resolve_reference(parsed.raw_query)

        # 1. If target object has matched OCR text
        if target_entity and target_entity.texts:
            texts = [f'"{t.text}"' for t in target_entity.texts]
            text = f"The visible text on the {target_entity.class_name} reads: {', '.join(texts)}."
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                target_entity=target_entity,
                sources=["ocr_engine", "context_manager"],
            )

        # 2. General scene OCR text
        if scene and scene.all_texts:
            texts = [f'"{t.text}"' for t in scene.all_texts]
            text = f"I detected the following text in the frame: {', '.join(texts)}."
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                sources=["ocr_engine"],
            )

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text="I do not see any legible text in the current frame.",
            sources=["ocr_engine"],
        )

    def _handle_reliability_check(self, parsed: ParsedQuery) -> ConversationResponse:
        target_entity = self.context_manager.resolve_reference(parsed.raw_query)
        if target_entity:
            rel_score = target_entity.reliability_score
            rel_label = target_entity.reliability_label or "evaluated"
            conf = target_entity.confidence
            if rel_score is not None:
                text = (
                    f"The detection of {target_entity.class_name} is labeled '{rel_label}' "
                    f"with an ANN reliability score of {rel_score:.2f} (YOLO confidence: {conf:.2f})."
                )
            else:
                text = f"The detection of {target_entity.class_name} has a YOLO confidence of {conf:.2f}."
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                target_entity=target_entity,
                sources=["reliability_ann", "vision_detector"],
            )

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text="Please specify which detected object you would like me to evaluate.",
            sources=["reliability_ann"],
        )

    def _handle_voice_control(self, parsed: ParsedQuery) -> ConversationResponse:
        q = parsed.raw_query.lower()
        if "clear memory" in q:
            self.context_manager.clear()
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text="Context and conversation memory have been cleared.",
            )

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text="Voice command acknowledged.",
        )

    def _handle_general_qa(self, parsed: ParsedQuery) -> ConversationResponse:
        # Check if there is an entity mentioned
        target_entity = self.context_manager.resolve_reference(parsed.raw_query)
        knowledge = None
        if target_entity:
            knowledge = self.knowledge_retriever.retrieve(target_entity.class_name)

        scene = self.context_manager.latest_scene
        scene_info = scene.summary() if scene else "No visual feed active."

        if knowledge:
            text = f"Regarding {knowledge.title}: {knowledge.summary}"
            sources = [knowledge.source, "context_manager"]
        elif target_entity:
            text = f"I am observing a {target_entity.describe()} in the scene."
            sources = ["context_manager"]
        else:
            text = f"Based on the visual scene ({scene_info}), I can provide assistance regarding visible objects or text."
            sources = ["context_manager"]

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            target_entity=target_entity,
            knowledge_item=knowledge,
            sources=sources,
        )
