"""
AURA Conversation & Reasoning Engine (Milestones 6 & 8)
Coordinates Context Manager, Knowledge Retriever, Episodic Memory, RAG Engine,
and Pluggable LLM reasoning providers to generate grounded, intelligent multimodal responses.
"""

import os
import time
import logging
from dataclasses import dataclass, field
from typing import Optional, List, Dict, Any

from knowledge.retriever import KnowledgeRetriever
from knowledge.sources import KnowledgeItem
from knowledge.rag import RAGEngine, RAGResult
from .context import ContextManager, ObjectEntity, SceneContext
from .intent import IntentClassifier, IntentType, ParsedQuery
from .memory import EpisodicMemory, EpisodicEvent
from .llm import BaseLLMProvider, OfflineReasoningProvider, create_llm_provider

logger = logging.getLogger(__name__)


@dataclass
class ConversationResponse:
    """
    Structured natural-language response generated by AURA.
    """
    query: str
    intent: IntentType
    response_text: str
    target_entity: Optional[ObjectEntity] = None
    knowledge_item: Optional[KnowledgeItem] = None
    rag_result: Optional[RAGResult] = None
    memory_event: Optional[EpisodicEvent] = None
    sources: List[str] = field(default_factory=list)
    timestamp: float = field(default_factory=time.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "query": self.query,
            "intent": self.intent.value,
            "response_text": self.response_text,
            "target_entity": self.target_entity.to_dict() if self.target_entity else None,
            "knowledge_item": self.knowledge_item.to_dict() if self.knowledge_item else None,
            "rag_result": self.rag_result.to_dict() if self.rag_result else None,
            "memory_event": self.memory_event.to_dict() if self.memory_event else None,
            "sources": self.sources,
            "timestamp": round(self.timestamp, 2),
        }


class ConversationEngine:
    """
    Core reasoning and conversational intelligence engine for AURA.
    Integrates real-time visual perception, episodic memory, document RAG, and LLM reasoning.
    """

    def __init__(
        self,
        context_manager: Optional[ContextManager] = None,
        knowledge_retriever: Optional[KnowledgeRetriever] = None,
        intent_classifier: Optional[IntentClassifier] = None,
        rag_engine: Optional[RAGEngine] = None,
        memory: Optional[EpisodicMemory] = None,
        llm_provider: Optional[BaseLLMProvider] = None,
    ):
        self.context_manager = context_manager or ContextManager()
        self.knowledge_retriever = knowledge_retriever or KnowledgeRetriever()
        self.intent_classifier = intent_classifier or IntentClassifier()
        self.rag_engine = rag_engine or RAGEngine()
        self.memory = memory or EpisodicMemory()
        self.llm_provider = llm_provider or OfflineReasoningProvider()

    def respond(self, query: str) -> ConversationResponse:
        """
        Processes a user question, parses intent, consults context, memory & RAG,
        and returns a grounded natural language response.
        """
        if not query or not query.strip():
            return ConversationResponse(
                query="",
                intent=IntentType.GENERAL_QA,
                response_text="I am listening. How can I assist you with what I see?",
            )

        # 1. Parse intent
        parsed = self.intent_classifier.classify(query)
        logger.info(f"Parsed intent '{parsed.intent.value}' for query: '{query}'")

        # 2. Record user query in conversation memory
        self.context_manager.add_conversation_turn("user", query)

        # 3. Route to specialized intent handlers
        if parsed.intent == IntentType.SCENE_SUMMARY:
            resp = self._handle_scene_summary(parsed)
        elif parsed.intent == IntentType.OBJECT_INFO:
            resp = self._handle_object_info(parsed)
        elif parsed.intent == IntentType.OBJECT_LOCATION:
            resp = self._handle_object_location(parsed)
        elif parsed.intent == IntentType.OBJECT_COUNT:
            resp = self._handle_object_count(parsed)
        elif parsed.intent == IntentType.OCR_READ:
            resp = self._handle_ocr_read(parsed)
        elif parsed.intent == IntentType.RELIABILITY_CHECK:
            resp = self._handle_reliability_check(parsed)
        elif parsed.intent == IntentType.MEMORY_SPATIAL:
            resp = self._handle_memory_spatial(parsed)
        elif parsed.intent == IntentType.MEMORY_TEMPORAL:
            resp = self._handle_memory_temporal(parsed)
        elif parsed.intent == IntentType.DOCUMENT_RAG:
            resp = self._handle_document_rag(parsed)
        elif parsed.intent == IntentType.VOICE_CONTROL:
            resp = self._handle_voice_control(parsed)
        else:
            resp = self._handle_general_qa(parsed)

        # 4. Record assistant response in conversation memory
        self.context_manager.add_conversation_turn("assistant", resp.response_text)
        return resp

    def _handle_scene_summary(self, parsed: ParsedQuery) -> ConversationResponse:
        scene = self.context_manager.latest_scene
        if not scene or not scene.entities:
            text = "The scene currently appears empty. No supported objects or text are currently detected."
        else:
            text = f"In the current frame, I observe: {scene.summary()}."

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            sources=["context_manager"],
        )

    def _handle_object_info(self, parsed: ParsedQuery) -> ConversationResponse:
        target_entity = None
        if parsed.target_object:
            target_entity = self.context_manager.get_entity_by_class(parsed.target_object)
        if not target_entity and parsed.track_id:
            target_entity = self.context_manager.get_entity_by_track_id(parsed.track_id)
        if not target_entity:
            target_entity = self.context_manager.resolve_reference(parsed.raw_query)

        # If entity is in current scene
        if target_entity:
            k_item = self.knowledge_retriever.retrieve(target_entity.class_name)
            ocr_text_str = ""
            if target_entity.ocr_texts:
                ocr_text_str = f" Extracted text: {', '.join([f'\"{t}\"' for t in target_entity.ocr_texts])}."

            if k_item:
                text = (
                    f"Identified {k_item.title} ({k_item.category}) in the {target_entity.spatial_region} of the scene "
                    f"with {int(target_entity.confidence * 100)}% detection certainty. {k_item.summary}{ocr_text_str}"
                )
                return ConversationResponse(
                    query=parsed.raw_query,
                    intent=parsed.intent,
                    response_text=text,
                    target_entity=target_entity,
                    knowledge_item=k_item,
                    sources=[k_item.source, "context_manager"],
                )
            else:
                text = f"I observe a {target_entity.describe()} in the {target_entity.spatial_region} region of the frame.{ocr_text_str}"
                return ConversationResponse(
                    query=parsed.raw_query,
                    intent=parsed.intent,
                    response_text=text,
                    target_entity=target_entity,
                    sources=["context_manager"],
                )

        # If not in scene, check knowledge base for general query
        lookup_name = parsed.target_object or parsed.raw_query
        k_item = self.knowledge_retriever.retrieve(lookup_name)
        if k_item:
            text = f"{k_item.title} ({k_item.category}): {k_item.summary}"
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                knowledge_item=k_item,
                sources=[k_item.source],
            )

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=f"No matching encyclopedic profile found for '{parsed.target_object or 'requested object'}'.",
            sources=["knowledge_retriever"],
        )

    def _handle_object_location(self, parsed: ParsedQuery) -> ConversationResponse:
        target_name = parsed.target_object or "object"
        entity = self.context_manager.get_entity_by_class(target_name)
        if not entity:
            entity = self.context_manager.resolve_reference(parsed.raw_query)

        if entity:
            text = f"The {entity.class_name} is currently located in the {entity.spatial_region} region of the frame."
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                target_entity=entity,
                sources=["context_manager"],
            )

        # Fallback to episodic memory if not in active view
        event = self.memory.find_last_seen(target_name)
        if event:
            text = (
                f"The {target_name} is not in the live view right now. "
                f"However, it was last observed in the {event.spatial_region} region {event.time_ago_str()}."
            )
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                memory_event=event,
                sources=["episodic_memory"],
            )

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=f"I cannot locate a {target_name} in the live scene or recent memory.",
            sources=["context_manager", "episodic_memory"],
        )

    def _handle_object_count(self, parsed: ParsedQuery) -> ConversationResponse:
        target_name = parsed.target_object
        scene = self.context_manager.latest_scene

        if not scene:
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text="No active visual stream to count objects.",
            )

        if target_name:
            count = scene.object_counts.get(target_name.lower(), 0)
            text = f"I count {count} {target_name}{'s' if count != 1 else ''} in the current frame."
        else:
            total = len(scene.entities)
            text = f"There are {total} total object{'s' if total != 1 else ''} in the current frame."

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            sources=["context_manager"],
        )

    def _handle_ocr_read(self, parsed: ParsedQuery) -> ConversationResponse:
        scene = self.context_manager.latest_scene
        target_entity = self.context_manager.resolve_reference(parsed.raw_query)

        # 1. If target object has matched OCR text
        if target_entity and target_entity.texts:
            texts = [f'"{t.text}"' for t in target_entity.texts]
            text = f"The visible text on the {target_entity.class_name} reads: {', '.join(texts)}."
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                target_entity=target_entity,
                sources=["ocr_engine", "context_manager"],
            )

        # 2. General scene OCR text
        if scene and scene.all_texts:
            texts = [f'"{t.text}"' for t in scene.all_texts]
            text = f"I detected the following text in the frame: {', '.join(texts)}."
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                sources=["ocr_engine"],
            )

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text="I do not see any legible text in the current frame.",
            sources=["ocr_engine"],
        )

    def _handle_reliability_check(self, parsed: ParsedQuery) -> ConversationResponse:
        target_entity = self.context_manager.resolve_reference(parsed.raw_query)
        if target_entity:
            rel_score = target_entity.reliability_score
            rel_label = target_entity.reliability_label or "evaluated"
            conf = target_entity.confidence
            if rel_score is not None:
                text = (
                    f"The detection of {target_entity.class_name} is labeled '{rel_label}' "
                    f"with an ANN reliability score of {rel_score:.2f} (YOLO confidence: {conf:.2f})."
                )
            else:
                text = f"The detection of {target_entity.class_name} has a YOLO confidence of {conf:.2f}."
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                target_entity=target_entity,
                sources=["reliability_ann", "vision_detector"],
            )

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text="Please specify which detected object you would like me to evaluate.",
            sources=["reliability_ann"],
        )

    def _handle_memory_spatial(self, parsed: ParsedQuery) -> ConversationResponse:
        """Handles 'Where was my <object>?' spatial memory recall."""
        target_name = parsed.target_object or "object"
        # Check active scene first
        active_entity = self.context_manager.get_entity_by_class(target_name)
        if active_entity:
            text = f"Your {active_entity.class_name} is right in front of you in the {active_entity.spatial_region} region."
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                target_entity=active_entity,
                sources=["context_manager"],
            )

        # Query persistent episodic memory
        text = self.memory.query_spatial_memory(target_name)
        event = self.memory.find_last_seen(target_name)
        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            memory_event=event,
            sources=["episodic_memory"],
        )

    def _handle_memory_temporal(self, parsed: ParsedQuery) -> ConversationResponse:
        """Handles 'When was <object> last seen?' temporal recall."""
        target_name = parsed.target_object or "person"
        text = self.memory.query_temporal_memory(target_name)
        event = self.memory.find_last_seen(target_name)
        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            memory_event=event,
            sources=["episodic_memory"],
        )

    def _handle_document_rag(self, parsed: ParsedQuery) -> ConversationResponse:
        """Handles document manuals, operating procedures, and safety guidelines queries."""
        rag_res = self.rag_engine.query(parsed.raw_query)

        if rag_res.has_results:
            top_doc = rag_res.top_document
            text = f"According to '{top_doc.title}': {top_doc.content}"
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=text,
                rag_result=rag_res,
                sources=["rag_vector_store"],
            )

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text="I searched the indexed documentation, but found no matching manual guidelines for this query.",
            sources=["rag_vector_store"],
        )

    def _handle_voice_control(self, parsed: ParsedQuery) -> ConversationResponse:
        q = parsed.raw_query.lower()
        if "clear memory" in q:
            self.context_manager.clear()
            self.memory.clear()
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text="Context and episodic memory have been completely cleared.",
            )

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text="Voice command acknowledged.",
        )

    def _handle_general_qa(self, parsed: ParsedQuery) -> ConversationResponse:
        # 1. Check if there is an entity mentioned in query or active scene
        target_entity = self.context_manager.resolve_reference(parsed.raw_query)
        knowledge = None
        if target_entity:
            knowledge = self.knowledge_retriever.retrieve(target_entity.class_name)
            if knowledge:
                return ConversationResponse(
                    query=parsed.raw_query,
                    intent=IntentType.OBJECT_INFO,
                    response_text=f"Identified {knowledge.title} ({knowledge.category}): {knowledge.summary}",
                    target_entity=target_entity,
                    knowledge_item=knowledge,
                    sources=[knowledge.source, "context_manager"],
                )

        # 2. Check if query matches a technical document in RAG with high confidence
        rag_res = self.rag_engine.query(parsed.raw_query)
        if rag_res.has_results and rag_res.scores[0] >= 0.60:
            top_doc = rag_res.top_document
            return ConversationResponse(
                query=parsed.raw_query,
                intent=parsed.intent,
                response_text=f"From '{top_doc.title}': {top_doc.content}",
                rag_result=rag_res,
                sources=["rag_vector_store"],
            )

        scene = self.context_manager.latest_scene
        scene_info = scene.summary() if scene else "No visual feed active."

        if knowledge:
            text = f"Regarding {knowledge.title}: {knowledge.summary}"
            sources = [knowledge.source, "context_manager"]
        elif target_entity:
            text = f"I am observing a {target_entity.describe()} in the scene."
            sources = ["context_manager"]
        else:
            text = f"Based on the visual scene ({scene_info}), I can provide assistance regarding visible objects, manuals, or memory."
            sources = ["context_manager"]

        return ConversationResponse(
            query=parsed.raw_query,
            intent=parsed.intent,
            response_text=text,
            target_entity=target_entity,
            knowledge_item=knowledge,
            sources=sources,
        )
